// Generated by Scripts/prepare-asc-spec.swift from Apple's spec (4.5.1). Do not edit.
// Every string enum in the spec's schemas: named ones (BundleIdPlatform) and inline ones in request
// schemas, named after their path (DeviceUpdateRequest → status: DeviceUpdateRequestStatus). The
// generated client carries these values as plain strings (see the prepare script); use the enums to
// validate input and to name values in code.

public enum ASCEnum {
  public enum AgeRatingDeclarationUpdateRequestAgeRatingOverride: String, CaseIterable, Sendable {
    case none = "NONE"
    case ninePlus = "NINE_PLUS"
    case thirteenPlus = "THIRTEEN_PLUS"
    case sixteenPlus = "SIXTEEN_PLUS"
    case seventeenPlus = "SEVENTEEN_PLUS"
    case unrated = "UNRATED"
  }

  public enum AgeRatingDeclarationUpdateRequestAgeRatingOverrideV2: String, CaseIterable, Sendable {
    case none = "NONE"
    case ninePlus = "NINE_PLUS"
    case thirteenPlus = "THIRTEEN_PLUS"
    case sixteenPlus = "SIXTEEN_PLUS"
    case eighteenPlus = "EIGHTEEN_PLUS"
    case unrated = "UNRATED"
  }

  public enum AgeRatingDeclarationUpdateRequestAlcoholTobaccoOrDrugUseOrReferences: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestContests: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestGamblingSimulated: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestGunsOrOtherWeapons: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestHorrorOrFearThemes: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestKoreaAgeRatingOverride: String, CaseIterable, Sendable {
    case none = "NONE"
    case all = "ALL"
    case twelvePlus = "TWELVE_PLUS"
    case fifteenPlus = "FIFTEEN_PLUS"
    case nineteenPlus = "NINETEEN_PLUS"
  }

  public enum AgeRatingDeclarationUpdateRequestMatureOrSuggestiveThemes: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestMedicalOrTreatmentInformation: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestProfanityOrCrudeHumor: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestSexualContentGraphicAndNudity: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestSexualContentOrNudity: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestViolenceCartoonOrFantasy: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestViolenceRealistic: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AgeRatingDeclarationUpdateRequestViolenceRealisticProlongedGraphicOrSadistic: String, CaseIterable, Sendable {
    case none = "NONE"
    case infrequentOrMild = "INFREQUENT_OR_MILD"
    case frequentOrIntense = "FREQUENT_OR_INTENSE"
    case infrequent = "INFREQUENT"
    case frequent = "FREQUENT"
  }

  public enum AnalyticsReportRequestCreateRequestAccessType: String, CaseIterable, Sendable {
    case oneTimeSnapshot = "ONE_TIME_SNAPSHOT"
    case ongoing = "ONGOING"
  }

  public enum AppAssetLibraryAssetCategory: String, CaseIterable, Sendable {
    case creativeAssets = "CREATIVE_ASSETS"
    case appScreenshotsAndPreviews = "APP_SCREENSHOTS_AND_PREVIEWS"
  }

  public enum AppAssetLibraryAssetState: String, CaseIterable, Sendable {
    case awaitingUpload = "AWAITING_UPLOAD"
    case uploadComplete = "UPLOAD_COMPLETE"
    case failed = "FAILED"
    case complete = "COMPLETE"
    case prepareForSubmission = "PREPARE_FOR_SUBMISSION"
    case readyForReview = "READY_FOR_REVIEW"
    case waitingForReview = "WAITING_FOR_REVIEW"
    case inReview = "IN_REVIEW"
    case accepted = "ACCEPTED"
    case approved = "APPROVED"
    case rejected = "REJECTED"
    case archived = "ARCHIVED"
  }

  public enum AppAssetLibraryDisplayClass: String, CaseIterable, Sendable {
    case `default` = "DEFAULT"
    case watchUltra = "WATCH_ULTRA"
    case watchSeries10 = "WATCH_SERIES_10"
    case watchSeries7 = "WATCH_SERIES_7"
    case watchSeries4 = "WATCH_SERIES_4"
    case watchSeries3 = "WATCH_SERIES_3"
    case iphoneDuo = "IPHONE_DUO"
    case iphoneDynamicIslandLargeDisplay = "IPHONE_DYNAMIC_ISLAND_LARGE_DISPLAY"
    case iphoneDynamicIslandMediumDisplay = "IPHONE_DYNAMIC_ISLAND_MEDIUM_DISPLAY"
    case iphoneFaceIdLargeDisplay = "IPHONE_FACE_ID_LARGE_DISPLAY"
    case iphoneFaceIdMediumDisplay = "IPHONE_FACE_ID_MEDIUM_DISPLAY"
    case iphoneHomeButtonLargeDisplay = "IPHONE_HOME_BUTTON_LARGE_DISPLAY"
    case iphoneHomeButtonMediumDisplay = "IPHONE_HOME_BUTTON_MEDIUM_DISPLAY"
    case iphoneHomeButton40Display = "IPHONE_HOME_BUTTON_40_DISPLAY"
    case iphoneHomeButton35Display = "IPHONE_HOME_BUTTON_35_DISPLAY"
    case ipad13Display = "IPAD_13_DISPLAY"
    case ipad11Display = "IPAD_11_DISPLAY"
    case ipad129Display = "IPAD_129_DISPLAY"
    case ipad105Display = "IPAD_105_DISPLAY"
    case ipad97Display = "IPAD_97_DISPLAY"
  }

  public enum AppAssetLibraryFeature: String, CaseIterable, Sendable {
    case appStoreVersions = "APP_STORE_VERSIONS"
    case customProductPages = "CUSTOM_PRODUCT_PAGES"
    case productPageOptimizations = "PRODUCT_PAGE_OPTIMIZATIONS"
    case inAppEvents = "IN_APP_EVENTS"
    case inAppPurchases = "IN_APP_PURCHASES"
    case subscriptions = "SUBSCRIPTIONS"
    case retentionMessaging = "RETENTION_MESSAGING"
    case gameCenter = "GAME_CENTER"
    case appClips = "APP_CLIPS"
    case appleAds = "APPLE_ADS"
  }

  public enum AppAssetLibraryMediaType: String, CaseIterable, Sendable {
    case image = "IMAGE"
    case video = "VIDEO"
  }

  public enum AppAssetLibraryPlacementPlatform: String, CaseIterable, Sendable {
    case iphoneAppStore = "IPHONE_APP_STORE"
    case ipadAppStore = "IPAD_APP_STORE"
    case watchAppStore = "WATCH_APP_STORE"
    case imessageAppStore = "IMESSAGE_APP_STORE"
    case visionProAppStore = "VISION_PRO_APP_STORE"
    case macAppStore = "MAC_APP_STORE"
    case tvAppStore = "TV_APP_STORE"
    case `any` = "ANY"
  }

  public enum AppAssetLibraryPlacementState: String, CaseIterable, Sendable {
    case assetProcessing = "ASSET_PROCESSING"
    case failed = "FAILED"
    case parentPrepareForSubmission = "PARENT_PREPARE_FOR_SUBMISSION"
    case parentReadyForReview = "PARENT_READY_FOR_REVIEW"
    case parentWaitingForReview = "PARENT_WAITING_FOR_REVIEW"
    case parentInReview = "PARENT_IN_REVIEW"
    case parentApproved = "PARENT_APPROVED"
  }

  public enum AppAssetLibraryPlacementType: String, CaseIterable, Sendable {
    case appScreenshot = "APP_SCREENSHOT"
    case imessageAppScreenshot = "IMESSAGE_APP_SCREENSHOT"
    case appPreview = "APP_PREVIEW"
    case productPageHeaderAsset = "PRODUCT_PAGE_HEADER_ASSET"
    case appStoreSearchResultsAsset = "APP_STORE_SEARCH_RESULTS_ASSET"
    case searchResultsAdsAsset = "SEARCH_RESULTS_ADS_ASSET"
    case todayTabAdsAsset = "TODAY_TAB_ADS_ASSET"
    case eventCardAsset = "EVENT_CARD_ASSET"
    case eventDetailsPageAsset = "EVENT_DETAILS_PAGE_ASSET"
    case retentionMessageAsset = "RETENTION_MESSAGE_ASSET"
  }

  public enum AppClipAction: String, CaseIterable, Sendable {
    case `open` = "OPEN"
    case view = "VIEW"
    case play = "PLAY"
  }

  public enum AppClipAdvancedExperienceCreateRequestBusinessCategory: String, CaseIterable, Sendable {
    case automotive = "AUTOMOTIVE"
    case beauty = "BEAUTY"
    case bikes = "BIKES"
    case books = "BOOKS"
    case casino = "CASINO"
    case education = "EDUCATION"
    case educationJapan = "EDUCATION_JAPAN"
    case entertainment = "ENTERTAINMENT"
    case evCharger = "EV_CHARGER"
    case financialUsd = "FINANCIAL_USD"
    case financialCny = "FINANCIAL_CNY"
    case financialGbp = "FINANCIAL_GBP"
    case financialJpy = "FINANCIAL_JPY"
    case financialEur = "FINANCIAL_EUR"
    case fitness = "FITNESS"
    case foodAndDrink = "FOOD_AND_DRINK"
    case gas = "GAS"
    case grocery = "GROCERY"
    case healthAndMedical = "HEALTH_AND_MEDICAL"
    case hotelAndTravel = "HOTEL_AND_TRAVEL"
    case music = "MUSIC"
    case parking = "PARKING"
    case petServices = "PET_SERVICES"
    case professionalServices = "PROFESSIONAL_SERVICES"
    case shopping = "SHOPPING"
    case ticketing = "TICKETING"
    case transit = "TRANSIT"
  }

  public enum AppClipAdvancedExperienceCreateRequestPlaceDisplayPointSource: String, CaseIterable, Sendable {
    case calculated = "CALCULATED"
    case manuallyPlaced = "MANUALLY_PLACED"
  }

  public enum AppClipAdvancedExperienceCreateRequestPlaceMapAction: String, CaseIterable, Sendable {
    case buyTickets = "BUY_TICKETS"
    case viewAvailability = "VIEW_AVAILABILITY"
    case viewPricing = "VIEW_PRICING"
    case hotelBookRoom = "HOTEL_BOOK_ROOM"
    case parkingReserveParking = "PARKING_RESERVE_PARKING"
    case restaurantJoinWaitlist = "RESTAURANT_JOIN_WAITLIST"
    case restaurantOrderDelivery = "RESTAURANT_ORDER_DELIVERY"
    case restaurantOrderFood = "RESTAURANT_ORDER_FOOD"
    case restaurantOrderTakeout = "RESTAURANT_ORDER_TAKEOUT"
    case restaurantReservation = "RESTAURANT_RESERVATION"
    case scheduleAppointment = "SCHEDULE_APPOINTMENT"
    case restaurantViewMenu = "RESTAURANT_VIEW_MENU"
    case theaterNowPlaying = "THEATER_NOW_PLAYING"
    case airlineBookTravel = "AIRLINE_BOOK_TRAVEL"
    case airlineCheckIn = "AIRLINE_CHECK_IN"
    case airlineFlightStatus = "AIRLINE_FLIGHT_STATUS"
    case apply = "APPLY"
    case book = "BOOK"
    case bookActivities = "BOOK_ACTIVITIES"
    case bookRides = "BOOK_RIDES"
    case bookTeetimes = "BOOK_TEETIMES"
    case bookTours = "BOOK_TOURS"
    case careers = "CAREERS"
    case chargeEv = "CHARGE_EV"
    case coupons = "COUPONS"
    case donate = "DONATE"
    case events = "EVENTS"
    case eventsShows = "EVENTS_SHOWS"
    case eventsSports = "EVENTS_SPORTS"
    case giftCard = "GIFT_CARD"
    case hotelAmenities = "HOTEL_AMENITIES"
    case join = "JOIN"
    case parkingAvailable = "PARKING_AVAILABLE"
    case restaurantPickup = "RESTAURANT_PICKUP"
    case retailServiceQuote = "RETAIL_SERVICE_QUOTE"
    case retailStoreDelivery = "RETAIL_STORE_DELIVERY"
    case retailStorePickup = "RETAIL_STORE_PICKUP"
    case retailStoreShop = "RETAIL_STORE_SHOP"
    case services = "SERVICES"
    case support = "SUPPORT"
    case payToPark = "PAY_TO_PARK"
  }

  public enum AppClipAdvancedExperienceCreateRequestPlacePhoneNumberType: String, CaseIterable, Sendable {
    case fax = "FAX"
    case landline = "LANDLINE"
    case mobile = "MOBILE"
    case tollfree = "TOLLFREE"
  }

  public enum AppClipAdvancedExperienceCreateRequestPlaceRelationship: String, CaseIterable, Sendable {
    case owner = "OWNER"
    case authorized = "AUTHORIZED"
    case other = "OTHER"
  }

  public enum AppClipAdvancedExperienceLanguage: String, CaseIterable, Sendable {
    case ar = "AR"
    case ca = "CA"
    case cs = "CS"
    case da = "DA"
    case de = "DE"
    case el = "EL"
    case en = "EN"
    case es = "ES"
    case fi = "FI"
    case fr = "FR"
    case he = "HE"
    case hi = "HI"
    case hr = "HR"
    case hu = "HU"
    case id = "ID"
    case it = "IT"
    case ja = "JA"
    case ko = "KO"
    case ms = "MS"
    case nl = "NL"
    case no = "NO"
    case pl = "PL"
    case pt = "PT"
    case ro = "RO"
    case ru = "RU"
    case sk = "SK"
    case sv = "SV"
    case th = "TH"
    case tr = "TR"
    case uk = "UK"
    case vi = "VI"
    case zh = "ZH"
  }

  public enum AppClipAdvancedExperienceUpdateRequestBusinessCategory: String, CaseIterable, Sendable {
    case automotive = "AUTOMOTIVE"
    case beauty = "BEAUTY"
    case bikes = "BIKES"
    case books = "BOOKS"
    case casino = "CASINO"
    case education = "EDUCATION"
    case educationJapan = "EDUCATION_JAPAN"
    case entertainment = "ENTERTAINMENT"
    case evCharger = "EV_CHARGER"
    case financialUsd = "FINANCIAL_USD"
    case financialCny = "FINANCIAL_CNY"
    case financialGbp = "FINANCIAL_GBP"
    case financialJpy = "FINANCIAL_JPY"
    case financialEur = "FINANCIAL_EUR"
    case fitness = "FITNESS"
    case foodAndDrink = "FOOD_AND_DRINK"
    case gas = "GAS"
    case grocery = "GROCERY"
    case healthAndMedical = "HEALTH_AND_MEDICAL"
    case hotelAndTravel = "HOTEL_AND_TRAVEL"
    case music = "MUSIC"
    case parking = "PARKING"
    case petServices = "PET_SERVICES"
    case professionalServices = "PROFESSIONAL_SERVICES"
    case shopping = "SHOPPING"
    case ticketing = "TICKETING"
    case transit = "TRANSIT"
  }

  public enum AppClipAdvancedExperienceUpdateRequestPlaceDisplayPointSource: String, CaseIterable, Sendable {
    case calculated = "CALCULATED"
    case manuallyPlaced = "MANUALLY_PLACED"
  }

  public enum AppClipAdvancedExperienceUpdateRequestPlaceMapAction: String, CaseIterable, Sendable {
    case buyTickets = "BUY_TICKETS"
    case viewAvailability = "VIEW_AVAILABILITY"
    case viewPricing = "VIEW_PRICING"
    case hotelBookRoom = "HOTEL_BOOK_ROOM"
    case parkingReserveParking = "PARKING_RESERVE_PARKING"
    case restaurantJoinWaitlist = "RESTAURANT_JOIN_WAITLIST"
    case restaurantOrderDelivery = "RESTAURANT_ORDER_DELIVERY"
    case restaurantOrderFood = "RESTAURANT_ORDER_FOOD"
    case restaurantOrderTakeout = "RESTAURANT_ORDER_TAKEOUT"
    case restaurantReservation = "RESTAURANT_RESERVATION"
    case scheduleAppointment = "SCHEDULE_APPOINTMENT"
    case restaurantViewMenu = "RESTAURANT_VIEW_MENU"
    case theaterNowPlaying = "THEATER_NOW_PLAYING"
    case airlineBookTravel = "AIRLINE_BOOK_TRAVEL"
    case airlineCheckIn = "AIRLINE_CHECK_IN"
    case airlineFlightStatus = "AIRLINE_FLIGHT_STATUS"
    case apply = "APPLY"
    case book = "BOOK"
    case bookActivities = "BOOK_ACTIVITIES"
    case bookRides = "BOOK_RIDES"
    case bookTeetimes = "BOOK_TEETIMES"
    case bookTours = "BOOK_TOURS"
    case careers = "CAREERS"
    case chargeEv = "CHARGE_EV"
    case coupons = "COUPONS"
    case donate = "DONATE"
    case events = "EVENTS"
    case eventsShows = "EVENTS_SHOWS"
    case eventsSports = "EVENTS_SPORTS"
    case giftCard = "GIFT_CARD"
    case hotelAmenities = "HOTEL_AMENITIES"
    case join = "JOIN"
    case parkingAvailable = "PARKING_AVAILABLE"
    case restaurantPickup = "RESTAURANT_PICKUP"
    case retailServiceQuote = "RETAIL_SERVICE_QUOTE"
    case retailStoreDelivery = "RETAIL_STORE_DELIVERY"
    case retailStorePickup = "RETAIL_STORE_PICKUP"
    case retailStoreShop = "RETAIL_STORE_SHOP"
    case services = "SERVICES"
    case support = "SUPPORT"
    case payToPark = "PAY_TO_PARK"
  }

  public enum AppClipAdvancedExperienceUpdateRequestPlacePhoneNumberType: String, CaseIterable, Sendable {
    case fax = "FAX"
    case landline = "LANDLINE"
    case mobile = "MOBILE"
    case tollfree = "TOLLFREE"
  }

  public enum AppClipAdvancedExperienceUpdateRequestPlaceRelationship: String, CaseIterable, Sendable {
    case owner = "OWNER"
    case authorized = "AUTHORIZED"
    case other = "OTHER"
  }

  public enum AppEncryptionDeclarationState: String, CaseIterable, Sendable {
    case created = "CREATED"
    case inReview = "IN_REVIEW"
    case approved = "APPROVED"
    case rejected = "REJECTED"
    case invalid = "INVALID"
    case expired = "EXPIRED"
  }

  public enum AppEventAssetType: String, CaseIterable, Sendable {
    case eventCard = "EVENT_CARD"
    case eventDetailsPage = "EVENT_DETAILS_PAGE"
  }

  public enum AppEventCreateRequestBadge: String, CaseIterable, Sendable {
    case liveEvent = "LIVE_EVENT"
    case premiere = "PREMIERE"
    case challenge = "CHALLENGE"
    case competition = "COMPETITION"
    case newSeason = "NEW_SEASON"
    case majorUpdate = "MAJOR_UPDATE"
    case specialEvent = "SPECIAL_EVENT"
  }

  public enum AppEventCreateRequestPriority: String, CaseIterable, Sendable {
    case high = "HIGH"
    case normal = "NORMAL"
  }

  public enum AppEventCreateRequestPurpose: String, CaseIterable, Sendable {
    case appropriateForAllUsers = "APPROPRIATE_FOR_ALL_USERS"
    case attractNewUsers = "ATTRACT_NEW_USERS"
    case keepActiveUsersInformed = "KEEP_ACTIVE_USERS_INFORMED"
    case bringBackLapsedUsers = "BRING_BACK_LAPSED_USERS"
  }

  public enum AppEventUpdateRequestBadge: String, CaseIterable, Sendable {
    case liveEvent = "LIVE_EVENT"
    case premiere = "PREMIERE"
    case challenge = "CHALLENGE"
    case competition = "COMPETITION"
    case newSeason = "NEW_SEASON"
    case majorUpdate = "MAJOR_UPDATE"
    case specialEvent = "SPECIAL_EVENT"
  }

  public enum AppEventUpdateRequestPriority: String, CaseIterable, Sendable {
    case high = "HIGH"
    case normal = "NORMAL"
  }

  public enum AppEventUpdateRequestPurpose: String, CaseIterable, Sendable {
    case appropriateForAllUsers = "APPROPRIATE_FOR_ALL_USERS"
    case attractNewUsers = "ATTRACT_NEW_USERS"
    case keepActiveUsersInformed = "KEEP_ACTIVE_USERS_INFORMED"
    case bringBackLapsedUsers = "BRING_BACK_LAPSED_USERS"
  }

  public enum AppStoreAgeRating: String, CaseIterable, Sendable {
    case l = "L"
    case all = "ALL"
    case zeroZero = "ZERO_ZERO"
    case onePlus = "ONE_PLUS"
    case twoPlus = "TWO_PLUS"
    case threePlus = "THREE_PLUS"
    case fourPlus = "FOUR_PLUS"
    case fivePlus = "FIVE_PLUS"
    case sixPlus = "SIX_PLUS"
    case sevenPlus = "SEVEN_PLUS"
    case eightPlus = "EIGHT_PLUS"
    case ninePlus = "NINE_PLUS"
    case tenPlus = "TEN_PLUS"
    case elevenPlus = "ELEVEN_PLUS"
    case twelvePlus = "TWELVE_PLUS"
    case thirteenPlus = "THIRTEEN_PLUS"
    case fourteenPlus = "FOURTEEN_PLUS"
    case fifteenPlus = "FIFTEEN_PLUS"
    case sixteenPlus = "SIXTEEN_PLUS"
    case seventeenPlus = "SEVENTEEN_PLUS"
    case eighteenPlus = "EIGHTEEN_PLUS"
    case nineteenPlus = "NINETEEN_PLUS"
    case twentyPlus = "TWENTY_PLUS"
    case twentyOnePlus = "TWENTY_ONE_PLUS"
    case unrated = "UNRATED"
  }

  public enum AppStoreVersionCreateRequestReleaseType: String, CaseIterable, Sendable {
    case manual = "MANUAL"
    case afterApproval = "AFTER_APPROVAL"
    case scheduled = "SCHEDULED"
  }

  public enum AppStoreVersionCreateRequestReviewType: String, CaseIterable, Sendable {
    case appStore = "APP_STORE"
    case notarization = "NOTARIZATION"
  }

  public enum AppStoreVersionState: String, CaseIterable, Sendable {
    case accepted = "ACCEPTED"
    case developerRemovedFromSale = "DEVELOPER_REMOVED_FROM_SALE"
    case developerRejected = "DEVELOPER_REJECTED"
    case inReview = "IN_REVIEW"
    case invalidBinary = "INVALID_BINARY"
    case metadataRejected = "METADATA_REJECTED"
    case pendingAppleRelease = "PENDING_APPLE_RELEASE"
    case pendingContract = "PENDING_CONTRACT"
    case pendingDeveloperRelease = "PENDING_DEVELOPER_RELEASE"
    case prepareForSubmission = "PREPARE_FOR_SUBMISSION"
    case preorderReadyForSale = "PREORDER_READY_FOR_SALE"
    case processingForAppStore = "PROCESSING_FOR_APP_STORE"
    case readyForReview = "READY_FOR_REVIEW"
    case readyForSale = "READY_FOR_SALE"
    case rejected = "REJECTED"
    case removedFromSale = "REMOVED_FROM_SALE"
    case waitingForExportCompliance = "WAITING_FOR_EXPORT_COMPLIANCE"
    case waitingForReview = "WAITING_FOR_REVIEW"
    case replacedWithNewVersion = "REPLACED_WITH_NEW_VERSION"
    case notApplicable = "NOT_APPLICABLE"
  }

  public enum AppStoreVersionUpdateRequestReleaseType: String, CaseIterable, Sendable {
    case manual = "MANUAL"
    case afterApproval = "AFTER_APPROVAL"
    case scheduled = "SCHEDULED"
  }

  public enum AppStoreVersionUpdateRequestReviewType: String, CaseIterable, Sendable {
    case appStore = "APP_STORE"
    case notarization = "NOTARIZATION"
  }

  public enum AppUpdateRequestContentRightsDeclaration: String, CaseIterable, Sendable {
    case doesNotUseThirdPartyContent = "DOES_NOT_USE_THIRD_PARTY_CONTENT"
    case usesThirdPartyContent = "USES_THIRD_PARTY_CONTENT"
  }

  public enum AppVersionState: String, CaseIterable, Sendable {
    case accepted = "ACCEPTED"
    case developerRejected = "DEVELOPER_REJECTED"
    case inReview = "IN_REVIEW"
    case invalidBinary = "INVALID_BINARY"
    case metadataRejected = "METADATA_REJECTED"
    case pendingAppleRelease = "PENDING_APPLE_RELEASE"
    case pendingDeveloperRelease = "PENDING_DEVELOPER_RELEASE"
    case prepareForSubmission = "PREPARE_FOR_SUBMISSION"
    case processingForDistribution = "PROCESSING_FOR_DISTRIBUTION"
    case readyForDistribution = "READY_FOR_DISTRIBUTION"
    case readyForReview = "READY_FOR_REVIEW"
    case rejected = "REJECTED"
    case replacedWithNewVersion = "REPLACED_WITH_NEW_VERSION"
    case waitingForExportCompliance = "WAITING_FOR_EXPORT_COMPLIANCE"
    case waitingForReview = "WAITING_FOR_REVIEW"
  }

  public enum BackgroundAssetUploadFileCreateRequestAssetType: String, CaseIterable, Sendable {
    case asset = "ASSET"
    case manifest = "MANIFEST"
  }

  public enum BackgroundAssetVersionAppStoreReleaseState: String, CaseIterable, Sendable {
    case prepareForSubmission = "PREPARE_FOR_SUBMISSION"
    case readyForReview = "READY_FOR_REVIEW"
    case waitingForReview = "WAITING_FOR_REVIEW"
    case inReview = "IN_REVIEW"
    case accepted = "ACCEPTED"
    case rejected = "REJECTED"
    case processingForDistribution = "PROCESSING_FOR_DISTRIBUTION"
    case readyForDistribution = "READY_FOR_DISTRIBUTION"
    case superseded = "SUPERSEDED"
  }

  public enum BackgroundAssetVersionExternalBetaReleaseState: String, CaseIterable, Sendable {
    case readyForBetaSubmission = "READY_FOR_BETA_SUBMISSION"
    case waitingForReview = "WAITING_FOR_REVIEW"
    case inReview = "IN_REVIEW"
    case rejected = "REJECTED"
    case processingForTesting = "PROCESSING_FOR_TESTING"
    case readyForTesting = "READY_FOR_TESTING"
    case superseded = "SUPERSEDED"
  }

  public enum BackgroundAssetVersionState: String, CaseIterable, Sendable {
    case awaitingUpload = "AWAITING_UPLOAD"
    case processing = "PROCESSING"
    case failed = "FAILED"
    case complete = "COMPLETE"
  }

  public enum BetaInviteType: String, CaseIterable, Sendable {
    case email = "EMAIL"
    case publicLink = "PUBLIC_LINK"
  }

  public enum BetaReviewState: String, CaseIterable, Sendable {
    case waitingForReview = "WAITING_FOR_REVIEW"
    case inReview = "IN_REVIEW"
    case rejected = "REJECTED"
    case approved = "APPROVED"
  }

  public enum BetaTesterState: String, CaseIterable, Sendable {
    case notInvited = "NOT_INVITED"
    case invited = "INVITED"
    case accepted = "ACCEPTED"
    case installed = "INSTALLED"
    case revoked = "REVOKED"
  }

  public enum BrazilAgeRating: String, CaseIterable, Sendable {
    case l = "L"
    case ten = "TEN"
    case twelve = "TWELVE"
    case fourteen = "FOURTEEN"
    case sixteen = "SIXTEEN"
    case eighteen = "EIGHTEEN"
  }

  public enum BuildAudienceType: String, CaseIterable, Sendable {
    case internalOnly = "INTERNAL_ONLY"
    case appStoreEligible = "APP_STORE_ELIGIBLE"
  }

  public enum BuildBundleType: String, CaseIterable, Sendable {
    case app = "APP"
    case appClip = "APP_CLIP"
    case watchApp = "WATCH_APP"
  }

  public enum BuildUploadFileCreateRequestAssetType: String, CaseIterable, Sendable {
    case asset = "ASSET"
    case assetDescription = "ASSET_DESCRIPTION"
    case assetSpi = "ASSET_SPI"
  }

  public enum BuildUploadFileCreateRequestUti: String, CaseIterable, Sendable {
    case comAppleBinaryPropertyList = "com.apple.binary-property-list"
    case comAppleIpa = "com.apple.ipa"
    case comApplePkg = "com.apple.pkg"
    case comAppleXmlPropertyList = "com.apple.xml-property-list"
    case comPkwareZipArchive = "com.pkware.zip-archive"
  }

  public enum BuildUploadState: String, CaseIterable, Sendable {
    case awaitingUpload = "AWAITING_UPLOAD"
    case processing = "PROCESSING"
    case failed = "FAILED"
    case complete = "COMPLETE"
  }

  public enum BundleIdPlatform: String, CaseIterable, Sendable {
    case ios = "IOS"
    case macOs = "MAC_OS"
    case universal = "UNIVERSAL"
  }

  public enum CapabilityType: String, CaseIterable, Sendable {
    case icloud = "ICLOUD"
    case inAppPurchase = "IN_APP_PURCHASE"
    case gameCenter = "GAME_CENTER"
    case pushNotifications = "PUSH_NOTIFICATIONS"
    case wallet = "WALLET"
    case interAppAudio = "INTER_APP_AUDIO"
    case maps = "MAPS"
    case associatedDomains = "ASSOCIATED_DOMAINS"
    case personalVpn = "PERSONAL_VPN"
    case appGroups = "APP_GROUPS"
    case healthkit = "HEALTHKIT"
    case homekit = "HOMEKIT"
    case wirelessAccessoryConfiguration = "WIRELESS_ACCESSORY_CONFIGURATION"
    case applePay = "APPLE_PAY"
    case dataProtection = "DATA_PROTECTION"
    case sirikit = "SIRIKIT"
    case networkExtensions = "NETWORK_EXTENSIONS"
    case multipath = "MULTIPATH"
    case hotSpot = "HOT_SPOT"
    case nfcTagReading = "NFC_TAG_READING"
    case classkit = "CLASSKIT"
    case autofillCredentialProvider = "AUTOFILL_CREDENTIAL_PROVIDER"
    case accessWifiInformation = "ACCESS_WIFI_INFORMATION"
    case networkCustomProtocol = "NETWORK_CUSTOM_PROTOCOL"
    case coremediaHlsLowLatency = "COREMEDIA_HLS_LOW_LATENCY"
    case systemExtensionInstall = "SYSTEM_EXTENSION_INSTALL"
    case userManagement = "USER_MANAGEMENT"
    case appleIdAuth = "APPLE_ID_AUTH"
  }

  public enum CertificateType: String, CaseIterable, Sendable {
    case applePay = "APPLE_PAY"
    case applePayMerchantIdentity = "APPLE_PAY_MERCHANT_IDENTITY"
    case applePayPspIdentity = "APPLE_PAY_PSP_IDENTITY"
    case applePayRsa = "APPLE_PAY_RSA"
    case developerIdKext = "DEVELOPER_ID_KEXT"
    case developerIdKextG2 = "DEVELOPER_ID_KEXT_G2"
    case developerIdApplication = "DEVELOPER_ID_APPLICATION"
    case developerIdApplicationG2 = "DEVELOPER_ID_APPLICATION_G2"
    case development = "DEVELOPMENT"
    case distribution = "DISTRIBUTION"
    case identityAccess = "IDENTITY_ACCESS"
    case iosDevelopment = "IOS_DEVELOPMENT"
    case iosDistribution = "IOS_DISTRIBUTION"
    case macAppDistribution = "MAC_APP_DISTRIBUTION"
    case macInstallerDistribution = "MAC_INSTALLER_DISTRIBUTION"
    case macAppDevelopment = "MAC_APP_DEVELOPMENT"
    case passTypeId = "PASS_TYPE_ID"
    case passTypeIdWithNfc = "PASS_TYPE_ID_WITH_NFC"
  }

  public enum ChecksumAlgorithm: String, CaseIterable, Sendable {
    case md5 = "MD5"
    case sha256 = "SHA_256"
  }

  public enum CiActionType: String, CaseIterable, Sendable {
    case build = "BUILD"
    case analyze = "ANALYZE"
    case test = "TEST"
    case archive = "ARCHIVE"
  }

  public enum CiCompletionStatus: String, CaseIterable, Sendable {
    case succeeded = "SUCCEEDED"
    case failed = "FAILED"
    case errored = "ERRORED"
    case canceled = "CANCELED"
    case skipped = "SKIPPED"
  }

  public enum CiExecutionProgress: String, CaseIterable, Sendable {
    case pending = "PENDING"
    case running = "RUNNING"
    case complete = "COMPLETE"
  }

  public enum CiGitRefKind: String, CaseIterable, Sendable {
    case branch = "BRANCH"
    case tag = "TAG"
  }

  public enum CiTestDestinationKind: String, CaseIterable, Sendable {
    case simulator = "SIMULATOR"
    case mac = "MAC"
  }

  public enum CiTestStatus: String, CaseIterable, Sendable {
    case success = "SUCCESS"
    case failure = "FAILURE"
    case mixed = "MIXED"
    case skipped = "SKIPPED"
    case expectedFailure = "EXPECTED_FAILURE"
  }

  public enum DeviceConnectionType: String, CaseIterable, Sendable {
    case wifi = "WIFI"
    case mobileData = "MOBILE_DATA"
    case wire = "WIRE"
    case unknown = "UNKNOWN"
    case none = "NONE"
  }

  public enum DeviceFamily: String, CaseIterable, Sendable {
    case iphone = "IPHONE"
    case ipad = "IPAD"
    case appleTv = "APPLE_TV"
    case appleWatch = "APPLE_WATCH"
    case mac = "MAC"
    case vision = "VISION"
  }

  public enum DeviceUpdateRequestStatus: String, CaseIterable, Sendable {
    case enabled = "ENABLED"
    case disabled = "DISABLED"
  }

  public enum DiagnosticInsightDirection: String, CaseIterable, Sendable {
    case up = "UP"
    case down = "DOWN"
    case undefined = "UNDEFINED"
  }

  public enum DiagnosticInsightType: String, CaseIterable, Sendable {
    case trend = "TREND"
  }

  public enum ExternalBetaState: String, CaseIterable, Sendable {
    case processing = "PROCESSING"
    case processingException = "PROCESSING_EXCEPTION"
    case missingExportCompliance = "MISSING_EXPORT_COMPLIANCE"
    case readyForBetaTesting = "READY_FOR_BETA_TESTING"
    case inBetaTesting = "IN_BETA_TESTING"
    case expired = "EXPIRED"
    case readyForBetaSubmission = "READY_FOR_BETA_SUBMISSION"
    case inExportComplianceReview = "IN_EXPORT_COMPLIANCE_REVIEW"
    case waitingForBetaReview = "WAITING_FOR_BETA_REVIEW"
    case inBetaReview = "IN_BETA_REVIEW"
    case betaRejected = "BETA_REJECTED"
    case betaApproved = "BETA_APPROVED"
    case notApplicable = "NOT_APPLICABLE"
  }

  public enum GameCenterActivityCreateRequestPlayStyle: String, CaseIterable, Sendable {
    case asynchronous = "ASYNCHRONOUS"
    case synchronous = "SYNCHRONOUS"
  }

  public enum GameCenterActivityUpdateRequestPlayStyle: String, CaseIterable, Sendable {
    case asynchronous = "ASYNCHRONOUS"
    case synchronous = "SYNCHRONOUS"
  }

  public enum GameCenterChallengeCreateRequestChallengeType: String, CaseIterable, Sendable {
    case leaderboard = "LEADERBOARD"
  }

  public enum GameCenterLeaderboardCreateRequestScoreSortType: String, CaseIterable, Sendable {
    case asc = "ASC"
    case desc = "DESC"
  }

  public enum GameCenterLeaderboardCreateRequestSubmissionType: String, CaseIterable, Sendable {
    case bestScore = "BEST_SCORE"
    case mostRecentScore = "MOST_RECENT_SCORE"
  }

  public enum GameCenterLeaderboardCreateRequestVisibility: String, CaseIterable, Sendable {
    case showForAll = "SHOW_FOR_ALL"
    case hideForAll = "HIDE_FOR_ALL"
  }

  public enum GameCenterLeaderboardFormatter: String, CaseIterable, Sendable {
    case integer = "INTEGER"
    case decimalPoint1Place = "DECIMAL_POINT_1_PLACE"
    case decimalPoint2Place = "DECIMAL_POINT_2_PLACE"
    case decimalPoint3Place = "DECIMAL_POINT_3_PLACE"
    case elapsedTimeCentisecond = "ELAPSED_TIME_CENTISECOND"
    case elapsedTimeMinute = "ELAPSED_TIME_MINUTE"
    case elapsedTimeSecond = "ELAPSED_TIME_SECOND"
    case moneyPoundDecimal = "MONEY_POUND_DECIMAL"
    case moneyPound = "MONEY_POUND"
    case moneyDollarDecimal = "MONEY_DOLLAR_DECIMAL"
    case moneyDollar = "MONEY_DOLLAR"
    case moneyEuroDecimal = "MONEY_EURO_DECIMAL"
    case moneyEuro = "MONEY_EURO"
    case moneyFrancDecimal = "MONEY_FRANC_DECIMAL"
    case moneyFranc = "MONEY_FRANC"
    case moneyKronerDecimal = "MONEY_KRONER_DECIMAL"
    case moneyKroner = "MONEY_KRONER"
    case moneyYen = "MONEY_YEN"
  }

  public enum GameCenterLeaderboardUpdateRequestScoreSortType: String, CaseIterable, Sendable {
    case asc = "ASC"
    case desc = "DESC"
  }

  public enum GameCenterLeaderboardUpdateRequestSubmissionType: String, CaseIterable, Sendable {
    case bestScore = "BEST_SCORE"
    case mostRecentScore = "MOST_RECENT_SCORE"
  }

  public enum GameCenterLeaderboardUpdateRequestVisibility: String, CaseIterable, Sendable {
    case showForAll = "SHOW_FOR_ALL"
    case hideForAll = "HIDE_FOR_ALL"
  }

  public enum GameCenterLeaderboardV2CreateRequestScoreSortType: String, CaseIterable, Sendable {
    case asc = "ASC"
    case desc = "DESC"
  }

  public enum GameCenterLeaderboardV2CreateRequestSubmissionType: String, CaseIterable, Sendable {
    case bestScore = "BEST_SCORE"
    case mostRecentScore = "MOST_RECENT_SCORE"
  }

  public enum GameCenterLeaderboardV2CreateRequestVisibility: String, CaseIterable, Sendable {
    case showForAll = "SHOW_FOR_ALL"
    case hideForAll = "HIDE_FOR_ALL"
  }

  public enum GameCenterLeaderboardV2UpdateRequestScoreSortType: String, CaseIterable, Sendable {
    case asc = "ASC"
    case desc = "DESC"
  }

  public enum GameCenterLeaderboardV2UpdateRequestSubmissionType: String, CaseIterable, Sendable {
    case bestScore = "BEST_SCORE"
    case mostRecentScore = "MOST_RECENT_SCORE"
  }

  public enum GameCenterLeaderboardV2UpdateRequestVisibility: String, CaseIterable, Sendable {
    case showForAll = "SHOW_FOR_ALL"
    case hideForAll = "HIDE_FOR_ALL"
  }

  public enum GameCenterMatchmakingRuleCreateRequestType: String, CaseIterable, Sendable {
    case compatible = "COMPATIBLE"
    case distance = "DISTANCE"
    case match = "MATCH"
    case team = "TEAM"
  }

  public enum GameCenterMatchmakingTestRequestInlineCreateLocale: String, CaseIterable, Sendable {
    case arSa = "AR-SA"
    case caEs = "CA-ES"
    case csCz = "CS-CZ"
    case daDk = "DA-DK"
    case deDe = "DE-DE"
    case elGr = "EL-GR"
    case enAu = "EN-AU"
    case enGb = "EN-GB"
    case enUs = "EN-US"
    case enKy = "EN-KY"
    case esEs = "ES-ES"
    case esMx = "ES-MX"
    case fiFi = "FI-FI"
    case frCa = "FR-CA"
    case frFr = "FR-FR"
    case hiIn = "HI-IN"
    case hrHr = "HR-HR"
    case huHu = "HU-HU"
    case idId = "ID-ID"
    case itIt = "IT-IT"
    case iwIl = "IW-IL"
    case jaJp = "JA-JP"
    case koKr = "KO-KR"
    case msMy = "MS-MY"
    case nlNl = "NL-NL"
    case noNo = "NO-NO"
    case plPl = "PL-PL"
    case ptBr = "PT-BR"
    case ptPt = "PT-PT"
    case roRo = "RO-RO"
    case ruRu = "RU-RU"
    case skSk = "SK-SK"
    case svSe = "SV-SE"
    case thTh = "TH-TH"
    case trTr = "TR-TR"
    case ukUa = "UK-UA"
    case zhCn = "ZH-CN"
    case zhTw = "ZH-TW"
    case zhHk = "ZH-HK"
  }

  public enum GameCenterVersionState: String, CaseIterable, Sendable {
    case prepareForSubmission = "PREPARE_FOR_SUBMISSION"
    case readyForReview = "READY_FOR_REVIEW"
    case waitingForReview = "WAITING_FOR_REVIEW"
    case inReview = "IN_REVIEW"
    case developerRejected = "DEVELOPER_REJECTED"
    case rejected = "REJECTED"
    case accepted = "ACCEPTED"
    case pendingRelease = "PENDING_RELEASE"
    case live = "LIVE"
    case replacedWithNewVersion = "REPLACED_WITH_NEW_VERSION"
  }

  public enum IconAssetType: String, CaseIterable, Sendable {
    case appStore = "APP_STORE"
    case messagesAppStore = "MESSAGES_APP_STORE"
    case watchAppStore = "WATCH_APP_STORE"
    case tvOsHomeScreen = "TV_OS_HOME_SCREEN"
    case tvOsTopShelf = "TV_OS_TOP_SHELF"
    case alternateExperiment = "ALTERNATE_EXPERIMENT"
  }

  public enum InAppPurchaseOfferCodeCreateRequestCustomerEligibilities: String, CaseIterable, Sendable {
    case nonSpender = "NON_SPENDER"
    case activeSpender = "ACTIVE_SPENDER"
    case churnedSpender = "CHURNED_SPENDER"
  }

  public enum InAppPurchaseState: String, CaseIterable, Sendable {
    case missingMetadata = "MISSING_METADATA"
    case waitingForUpload = "WAITING_FOR_UPLOAD"
    case processingContent = "PROCESSING_CONTENT"
    case readyToSubmit = "READY_TO_SUBMIT"
    case waitingForReview = "WAITING_FOR_REVIEW"
    case inReview = "IN_REVIEW"
    case developerActionNeeded = "DEVELOPER_ACTION_NEEDED"
    case pendingBinaryApproval = "PENDING_BINARY_APPROVAL"
    case approved = "APPROVED"
    case developerRemovedFromSale = "DEVELOPER_REMOVED_FROM_SALE"
    case removedFromSale = "REMOVED_FROM_SALE"
    case rejected = "REJECTED"
  }

  public enum InAppPurchaseType: String, CaseIterable, Sendable {
    case consumable = "CONSUMABLE"
    case nonConsumable = "NON_CONSUMABLE"
    case nonRenewingSubscription = "NON_RENEWING_SUBSCRIPTION"
  }

  public enum InternalBetaState: String, CaseIterable, Sendable {
    case processing = "PROCESSING"
    case processingException = "PROCESSING_EXCEPTION"
    case missingExportCompliance = "MISSING_EXPORT_COMPLIANCE"
    case readyForBetaTesting = "READY_FOR_BETA_TESTING"
    case inBetaTesting = "IN_BETA_TESTING"
    case expired = "EXPIRED"
    case inExportComplianceReview = "IN_EXPORT_COMPLIANCE_REVIEW"
  }

  public enum KidsAgeBand: String, CaseIterable, Sendable {
    case fiveAndUnder = "FIVE_AND_UNDER"
    case sixToEight = "SIX_TO_EIGHT"
    case nineToEleven = "NINE_TO_ELEVEN"
  }

  public enum MetricCategory: String, CaseIterable, Sendable {
    case hang = "HANG"
    case launch = "LAUNCH"
    case memory = "MEMORY"
    case disk = "DISK"
    case battery = "BATTERY"
    case termination = "TERMINATION"
    case animation = "ANIMATION"
    case storage = "STORAGE"
  }

  public enum NominationCreateRequestType: String, CaseIterable, Sendable {
    case appLaunch = "APP_LAUNCH"
    case appEnhancements = "APP_ENHANCEMENTS"
    case newContent = "NEW_CONTENT"
  }

  public enum NominationUpdateRequestType: String, CaseIterable, Sendable {
    case appLaunch = "APP_LAUNCH"
    case appEnhancements = "APP_ENHANCEMENTS"
    case newContent = "NEW_CONTENT"
  }

  public enum OfferCodeEnvironment: String, CaseIterable, Sendable {
    case production = "PRODUCTION"
    case sandbox = "SANDBOX"
  }

  public enum PhasedReleaseState: String, CaseIterable, Sendable {
    case inactive = "INACTIVE"
    case active = "ACTIVE"
    case paused = "PAUSED"
    case complete = "COMPLETE"
  }

  public enum Platform: String, CaseIterable, Sendable {
    case ios = "IOS"
    case macOs = "MAC_OS"
    case tvOs = "TV_OS"
    case visionOs = "VISION_OS"
  }

  public enum PreviewType: String, CaseIterable, Sendable {
    case iphone67 = "IPHONE_67"
    case iphone61 = "IPHONE_61"
    case iphone65 = "IPHONE_65"
    case iphone58 = "IPHONE_58"
    case iphone55 = "IPHONE_55"
    case iphone47 = "IPHONE_47"
    case iphone40 = "IPHONE_40"
    case iphone35 = "IPHONE_35"
    case ipadPro3gen129 = "IPAD_PRO_3GEN_129"
    case ipadPro3gen11 = "IPAD_PRO_3GEN_11"
    case ipadPro129 = "IPAD_PRO_129"
    case ipad105 = "IPAD_105"
    case ipad97 = "IPAD_97"
    case desktop = "DESKTOP"
    case appleTv = "APPLE_TV"
    case appleVisionPro = "APPLE_VISION_PRO"
  }

  public enum ProfileCreateRequestProfileType: String, CaseIterable, Sendable {
    case iosAppDevelopment = "IOS_APP_DEVELOPMENT"
    case iosAppStore = "IOS_APP_STORE"
    case iosAppAdhoc = "IOS_APP_ADHOC"
    case iosAppInhouse = "IOS_APP_INHOUSE"
    case macAppDevelopment = "MAC_APP_DEVELOPMENT"
    case macAppStore = "MAC_APP_STORE"
    case macAppDirect = "MAC_APP_DIRECT"
    case tvosAppDevelopment = "TVOS_APP_DEVELOPMENT"
    case tvosAppStore = "TVOS_APP_STORE"
    case tvosAppAdhoc = "TVOS_APP_ADHOC"
    case tvosAppInhouse = "TVOS_APP_INHOUSE"
    case macCatalystAppDevelopment = "MAC_CATALYST_APP_DEVELOPMENT"
    case macCatalystAppStore = "MAC_CATALYST_APP_STORE"
    case macCatalystAppDirect = "MAC_CATALYST_APP_DIRECT"
  }

  public enum SandboxTesterV2UpdateRequestSubscriptionRenewalRate: String, CaseIterable, Sendable {
    case monthlyRenewalEveryOneHour = "MONTHLY_RENEWAL_EVERY_ONE_HOUR"
    case monthlyRenewalEveryThirtyMinutes = "MONTHLY_RENEWAL_EVERY_THIRTY_MINUTES"
    case monthlyRenewalEveryFifteenMinutes = "MONTHLY_RENEWAL_EVERY_FIFTEEN_MINUTES"
    case monthlyRenewalEveryFiveMinutes = "MONTHLY_RENEWAL_EVERY_FIVE_MINUTES"
    case monthlyRenewalEveryThreeMinutes = "MONTHLY_RENEWAL_EVERY_THREE_MINUTES"
  }

  public enum ScreenshotDisplayType: String, CaseIterable, Sendable {
    case appIphone67 = "APP_IPHONE_67"
    case appIphone61 = "APP_IPHONE_61"
    case appIphone65 = "APP_IPHONE_65"
    case appIphone58 = "APP_IPHONE_58"
    case appIphone55 = "APP_IPHONE_55"
    case appIphone47 = "APP_IPHONE_47"
    case appIphone40 = "APP_IPHONE_40"
    case appIphone35 = "APP_IPHONE_35"
    case appIpadPro3gen129 = "APP_IPAD_PRO_3GEN_129"
    case appIpadPro3gen11 = "APP_IPAD_PRO_3GEN_11"
    case appIpadPro129 = "APP_IPAD_PRO_129"
    case appIpad105 = "APP_IPAD_105"
    case appIpad97 = "APP_IPAD_97"
    case appDesktop = "APP_DESKTOP"
    case appWatchUltra = "APP_WATCH_ULTRA"
    case appWatchSeries10 = "APP_WATCH_SERIES_10"
    case appWatchSeries7 = "APP_WATCH_SERIES_7"
    case appWatchSeries4 = "APP_WATCH_SERIES_4"
    case appWatchSeries3 = "APP_WATCH_SERIES_3"
    case appAppleTv = "APP_APPLE_TV"
    case appAppleVisionPro = "APP_APPLE_VISION_PRO"
    case imessageAppIphone67 = "IMESSAGE_APP_IPHONE_67"
    case imessageAppIphone61 = "IMESSAGE_APP_IPHONE_61"
    case imessageAppIphone65 = "IMESSAGE_APP_IPHONE_65"
    case imessageAppIphone58 = "IMESSAGE_APP_IPHONE_58"
    case imessageAppIphone55 = "IMESSAGE_APP_IPHONE_55"
    case imessageAppIphone47 = "IMESSAGE_APP_IPHONE_47"
    case imessageAppIphone40 = "IMESSAGE_APP_IPHONE_40"
    case imessageAppIpadPro3gen129 = "IMESSAGE_APP_IPAD_PRO_3GEN_129"
    case imessageAppIpadPro3gen11 = "IMESSAGE_APP_IPAD_PRO_3GEN_11"
    case imessageAppIpadPro129 = "IMESSAGE_APP_IPAD_PRO_129"
    case imessageAppIpad105 = "IMESSAGE_APP_IPAD_105"
    case imessageAppIpad97 = "IMESSAGE_APP_IPAD_97"
  }

  public enum SubscriptionCreateRequestSubscriptionPeriod: String, CaseIterable, Sendable {
    case oneWeek = "ONE_WEEK"
    case oneMonth = "ONE_MONTH"
    case twoMonths = "TWO_MONTHS"
    case threeMonths = "THREE_MONTHS"
    case sixMonths = "SIX_MONTHS"
    case oneYear = "ONE_YEAR"
  }

  public enum SubscriptionCustomerEligibility: String, CaseIterable, Sendable {
    case new = "NEW"
    case existing = "EXISTING"
    case expired = "EXPIRED"
  }

  public enum SubscriptionGracePeriodDuration: String, CaseIterable, Sendable {
    case threeDays = "THREE_DAYS"
    case sixteenDays = "SIXTEEN_DAYS"
    case twentyEightDays = "TWENTY_EIGHT_DAYS"
  }

  public enum SubscriptionGracePeriodUpdateRequestRenewalType: String, CaseIterable, Sendable {
    case allRenewals = "ALL_RENEWALS"
    case paidToPaidOnly = "PAID_TO_PAID_ONLY"
  }

  public enum SubscriptionOfferDuration: String, CaseIterable, Sendable {
    case threeDays = "THREE_DAYS"
    case oneWeek = "ONE_WEEK"
    case twoWeeks = "TWO_WEEKS"
    case oneMonth = "ONE_MONTH"
    case twoMonths = "TWO_MONTHS"
    case threeMonths = "THREE_MONTHS"
    case sixMonths = "SIX_MONTHS"
    case oneYear = "ONE_YEAR"
  }

  public enum SubscriptionOfferEligibility: String, CaseIterable, Sendable {
    case stackWithIntroOffers = "STACK_WITH_INTRO_OFFERS"
    case replaceIntroOffers = "REPLACE_INTRO_OFFERS"
  }

  public enum SubscriptionOfferMode: String, CaseIterable, Sendable {
    case payAsYouGo = "PAY_AS_YOU_GO"
    case payUpFront = "PAY_UP_FRONT"
    case freeTrial = "FREE_TRIAL"
  }

  public enum SubscriptionPlanType: String, CaseIterable, Sendable {
    case monthly = "MONTHLY"
    case upfront = "UPFRONT"
  }

  public enum SubscriptionStatusUrlVersion: String, CaseIterable, Sendable {
    case v1 = "V1"
    case v2 = "V2"
  }

  public enum SubscriptionUpdateRequestMarketSettings: String, CaseIterable, Sendable {
    case appleSchool = "APPLE_SCHOOL"
    case appStore = "APP_STORE"
    case appleBusiness = "APPLE_BUSINESS"
  }

  public enum SubscriptionUpdateRequestMultiSeatStatus: String, CaseIterable, Sendable {
    case enabled = "ENABLED"
    case disabled = "DISABLED"
  }

  public enum SubscriptionUpdateRequestSubscriptionPeriod: String, CaseIterable, Sendable {
    case oneWeek = "ONE_WEEK"
    case oneMonth = "ONE_MONTH"
    case twoMonths = "TWO_MONTHS"
    case threeMonths = "THREE_MONTHS"
    case sixMonths = "SIX_MONTHS"
    case oneYear = "ONE_YEAR"
  }

  public enum TerritoryCode: String, CaseIterable, Sendable {
    case abw = "ABW"
    case afg = "AFG"
    case ago = "AGO"
    case aia = "AIA"
    case alb = "ALB"
    case and = "AND"
    case ant = "ANT"
    case are = "ARE"
    case arg = "ARG"
    case arm = "ARM"
    case asm = "ASM"
    case atg = "ATG"
    case aus = "AUS"
    case aut = "AUT"
    case aze = "AZE"
    case bdi = "BDI"
    case bel = "BEL"
    case ben = "BEN"
    case bes = "BES"
    case bfa = "BFA"
    case bgd = "BGD"
    case bgr = "BGR"
    case bhr = "BHR"
    case bhs = "BHS"
    case bih = "BIH"
    case blr = "BLR"
    case blz = "BLZ"
    case bmu = "BMU"
    case bol = "BOL"
    case bra = "BRA"
    case brb = "BRB"
    case brn = "BRN"
    case btn = "BTN"
    case bwa = "BWA"
    case caf = "CAF"
    case can = "CAN"
    case che = "CHE"
    case chl = "CHL"
    case chn = "CHN"
    case civ = "CIV"
    case cmr = "CMR"
    case cod = "COD"
    case cog = "COG"
    case cok = "COK"
    case col = "COL"
    case com = "COM"
    case cpv = "CPV"
    case cri = "CRI"
    case cub = "CUB"
    case cuw = "CUW"
    case cxr = "CXR"
    case cym = "CYM"
    case cyp = "CYP"
    case cze = "CZE"
    case deu = "DEU"
    case dji = "DJI"
    case dma = "DMA"
    case dnk = "DNK"
    case dom = "DOM"
    case dza = "DZA"
    case ecu = "ECU"
    case egy = "EGY"
    case eri = "ERI"
    case esp = "ESP"
    case est = "EST"
    case eth = "ETH"
    case fin = "FIN"
    case fji = "FJI"
    case flk = "FLK"
    case fra = "FRA"
    case fro = "FRO"
    case fsm = "FSM"
    case gab = "GAB"
    case gbr = "GBR"
    case geo = "GEO"
    case ggy = "GGY"
    case gha = "GHA"
    case gib = "GIB"
    case gin = "GIN"
    case glp = "GLP"
    case gmb = "GMB"
    case gnb = "GNB"
    case gnq = "GNQ"
    case grc = "GRC"
    case grd = "GRD"
    case grl = "GRL"
    case gtm = "GTM"
    case guf = "GUF"
    case gum = "GUM"
    case guy = "GUY"
    case hkg = "HKG"
    case hnd = "HND"
    case hrv = "HRV"
    case hti = "HTI"
    case hun = "HUN"
    case idn = "IDN"
    case imn = "IMN"
    case ind = "IND"
    case irl = "IRL"
    case irq = "IRQ"
    case isl = "ISL"
    case isr = "ISR"
    case ita = "ITA"
    case jam = "JAM"
    case jey = "JEY"
    case jor = "JOR"
    case jpn = "JPN"
    case kaz = "KAZ"
    case ken = "KEN"
    case kgz = "KGZ"
    case khm = "KHM"
    case kir = "KIR"
    case kna = "KNA"
    case kor = "KOR"
    case kwt = "KWT"
    case lao = "LAO"
    case lbn = "LBN"
    case lbr = "LBR"
    case lby = "LBY"
    case lca = "LCA"
    case lie = "LIE"
    case lka = "LKA"
    case lso = "LSO"
    case ltu = "LTU"
    case lux = "LUX"
    case lva = "LVA"
    case mac = "MAC"
    case mar = "MAR"
    case mco = "MCO"
    case mda = "MDA"
    case mdg = "MDG"
    case mdv = "MDV"
    case mex = "MEX"
    case mhl = "MHL"
    case mkd = "MKD"
    case mli = "MLI"
    case mlt = "MLT"
    case mmr = "MMR"
    case mne = "MNE"
    case mng = "MNG"
    case mnp = "MNP"
    case moz = "MOZ"
    case mrt = "MRT"
    case msr = "MSR"
    case mtq = "MTQ"
    case mus = "MUS"
    case mwi = "MWI"
    case mys = "MYS"
    case myt = "MYT"
    case nam = "NAM"
    case ncl = "NCL"
    case ner = "NER"
    case nfk = "NFK"
    case nga = "NGA"
    case nic = "NIC"
    case niu = "NIU"
    case nld = "NLD"
    case nor = "NOR"
    case npl = "NPL"
    case nru = "NRU"
    case nzl = "NZL"
    case omn = "OMN"
    case pak = "PAK"
    case pan = "PAN"
    case per = "PER"
    case phl = "PHL"
    case plw = "PLW"
    case png = "PNG"
    case pol = "POL"
    case pri = "PRI"
    case prt = "PRT"
    case pry = "PRY"
    case pse = "PSE"
    case pyf = "PYF"
    case qat = "QAT"
    case reu = "REU"
    case rou = "ROU"
    case rus = "RUS"
    case rwa = "RWA"
    case sau = "SAU"
    case sen = "SEN"
    case sgp = "SGP"
    case shn = "SHN"
    case slb = "SLB"
    case sle = "SLE"
    case slv = "SLV"
    case smr = "SMR"
    case som = "SOM"
    case spm = "SPM"
    case srb = "SRB"
    case ssd = "SSD"
    case stp = "STP"
    case sur = "SUR"
    case svk = "SVK"
    case svn = "SVN"
    case swe = "SWE"
    case swz = "SWZ"
    case sxm = "SXM"
    case syc = "SYC"
    case tca = "TCA"
    case tcd = "TCD"
    case tgo = "TGO"
    case tha = "THA"
    case tjk = "TJK"
    case tkm = "TKM"
    case tls = "TLS"
    case ton = "TON"
    case tto = "TTO"
    case tun = "TUN"
    case tur = "TUR"
    case tuv = "TUV"
    case twn = "TWN"
    case tza = "TZA"
    case uga = "UGA"
    case ukr = "UKR"
    case umi = "UMI"
    case ury = "URY"
    case usa = "USA"
    case uzb = "UZB"
    case vat = "VAT"
    case vct = "VCT"
    case ven = "VEN"
    case vgb = "VGB"
    case vir = "VIR"
    case vnm = "VNM"
    case vut = "VUT"
    case wlf = "WLF"
    case wsm = "WSM"
    case xks = "XKS"
    case yem = "YEM"
    case zaf = "ZAF"
    case zmb = "ZMB"
    case zwe = "ZWE"
  }

  public enum UserRole: String, CaseIterable, Sendable {
    case admin = "ADMIN"
    case finance = "FINANCE"
    case accountHolder = "ACCOUNT_HOLDER"
    case sales = "SALES"
    case marketing = "MARKETING"
    case appManager = "APP_MANAGER"
    case developer = "DEVELOPER"
    case accessToReports = "ACCESS_TO_REPORTS"
    case customerSupport = "CUSTOMER_SUPPORT"
    case createApps = "CREATE_APPS"
    case cloudManagedDeveloperId = "CLOUD_MANAGED_DEVELOPER_ID"
    case cloudManagedAppDistribution = "CLOUD_MANAGED_APP_DISTRIBUTION"
    case generateIndividualKeys = "GENERATE_INDIVIDUAL_KEYS"
  }

  public enum WebhookEventType: String, CaseIterable, Sendable {
    case alternativeDistributionPackageAvailableUpdated = "ALTERNATIVE_DISTRIBUTION_PACKAGE_AVAILABLE_UPDATED"
    case alternativeDistributionPackageVersionCreated = "ALTERNATIVE_DISTRIBUTION_PACKAGE_VERSION_CREATED"
    case alternativeDistributionTerritoryAvailabilityUpdated = "ALTERNATIVE_DISTRIBUTION_TERRITORY_AVAILABILITY_UPDATED"
    case appStoreVersionAppVersionStateUpdated = "APP_STORE_VERSION_APP_VERSION_STATE_UPDATED"
    case backgroundAssetVersionAppStoreReleaseStateUpdated = "BACKGROUND_ASSET_VERSION_APP_STORE_RELEASE_STATE_UPDATED"
    case backgroundAssetVersionExternalBetaReleaseStateUpdated = "BACKGROUND_ASSET_VERSION_EXTERNAL_BETA_RELEASE_STATE_UPDATED"
    case backgroundAssetVersionInternalBetaReleaseCreated = "BACKGROUND_ASSET_VERSION_INTERNAL_BETA_RELEASE_CREATED"
    case backgroundAssetVersionStateUpdated = "BACKGROUND_ASSET_VERSION_STATE_UPDATED"
    case betaFeedbackCrashSubmissionCreated = "BETA_FEEDBACK_CRASH_SUBMISSION_CREATED"
    case betaFeedbackScreenshotSubmissionCreated = "BETA_FEEDBACK_SCREENSHOT_SUBMISSION_CREATED"
    case buildBetaDetailExternalBuildStateUpdated = "BUILD_BETA_DETAIL_EXTERNAL_BUILD_STATE_UPDATED"
    case buildUploadStateUpdated = "BUILD_UPLOAD_STATE_UPDATED"
  }

  public enum WinBackOfferCreateRequestPriority: String, CaseIterable, Sendable {
    case high = "HIGH"
    case normal = "NORMAL"
  }

  public enum WinBackOfferCreateRequestPromotionIntent: String, CaseIterable, Sendable {
    case notPromoted = "NOT_PROMOTED"
    case useAutoGeneratedAssets = "USE_AUTO_GENERATED_ASSETS"
  }

  public enum WinBackOfferUpdateRequestPriority: String, CaseIterable, Sendable {
    case high = "HIGH"
    case normal = "NORMAL"
  }

  public enum WinBackOfferUpdateRequestPromotionIntent: String, CaseIterable, Sendable {
    case notPromoted = "NOT_PROMOTED"
    case useAutoGeneratedAssets = "USE_AUTO_GENERATED_ASSETS"
  }
}
