import CryptoKit
import Foundation
import HTTPTypes
import OpenAPIRuntime
import OpenAPIURLSession

// App Store Connect API client generated by swift-openapi-generator from Apple's own spec
// (openapi.json, prepared by Scripts/prepare-asc-spec.swift; generated paths are listed in
// openapi-generator-config.yaml). It replaces asc-swift one command at a time.

public typealias ASCClient = Client

public struct ASCCredentials: Sendable {
  public let keyID: String
  public let issuerID: String
  public let privateKeyPEM: String

  public init(keyID: String, issuerID: String, privateKeyPEM: String) {
    self.keyID = keyID
    self.issuerID = issuerID
    self.privateKeyPEM = privateKeyPEM
  }
}

extension Client {
  /// A client for api.appstoreconnect.apple.com: every request is signed with a JWT, every error
  /// response is thrown as an `ASCError`, and `ASCPaging.allPages` can follow `links.next`.
  /// With `dryRun`, GETs go out as usual but every other request is stopped before it is sent
  /// and reported on stderr (method, path, JSON body), surfacing as `ASCDryRunStop`.
  public static func appStoreConnect(
    credentials: ASCCredentials, dryRun: Bool = false, rateLimitWait: ASCRateLimitWait? = nil
  ) throws -> Client {
    let key = try P256.Signing.PrivateKey(pemRepresentation: credentials.privateKeyPEM)
    var middlewares: [any ClientMiddleware] = [ErrorMiddleware()]
    // Inside the error middleware, to see a 429 before it becomes an error; outside JWT signing,
    // so a request sent again after a long wait gets a fresh token.
    if let rateLimitWait { middlewares.append(RateLimitWaitMiddleware(policy: rateLimitWait)) }
    middlewares += [
      PagingMiddleware(),
      NullsMiddleware(),
      JWTMiddleware(tokens: TokenStore(credentials: credentials, key: key)),
    ]
    if dryRun { middlewares.append(DryRunMiddleware()) }
    return Client(
      serverURL: try Servers.Server1.url(),
      configuration: Configuration(dateTranscoder: FlexibleISO8601DateTranscoder()),
      transport: URLSessionTransport(),
      middlewares: middlewares
    )
  }
}

// MARK: - Dry run

/// A mutating request a dry-run client refused to send.
public struct ASCDryRunStop: Error, Sendable, CustomStringConvertible {
  public let method: String
  public let path: String

  public var description: String { "Dry run: \(method) \(path) was not sent." }

  /// The `ASCDryRunStop` behind an error thrown by a generated operation, or nil.
  public static func from(_ error: Error) -> ASCDryRunStop? {
    if let stop = error as? ASCDryRunStop { return stop }
    return (error as? ClientError)?.underlyingError as? ASCDryRunStop
  }
}

/// How many writes dry-run clients have stopped in this process, so a caller can tell a
/// failure caused only by dry run from a real one.
public enum ASCDryRun {
  private final class Counter: @unchecked Sendable {
    private let lock = NSLock()
    private var value = 0

    var count: Int { lock.withLock { value } }
    func increment() { lock.withLock { value += 1 } }
  }

  private static let counter = Counter()

  public static var blockedWrites: Int { counter.count }
  static func recordBlockedWrite() { counter.increment() }
}

struct DryRunMiddleware: ClientMiddleware {
  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    guard request.method != .get else { return try await next(request, body, baseURL) }
    let path = request.path ?? "?"
    var report = "[dry-run] \(request.method.rawValue) \(path)"
    if let body {
      let data = try await Data(collecting: body, upTo: 16 << 20)
      if let json = try? JSONSerialization.jsonObject(with: data),
        let pretty = try? JSONSerialization.data(withJSONObject: json, options: [.prettyPrinted, .sortedKeys]) {
        report += "\n" + String(decoding: pretty, as: UTF8.self)
      } else if !data.isEmpty {
        report += "\n" + String(decoding: data, as: UTF8.self)
      }
    }
    FileHandle.standardError.write(Data((report + "\n").utf8))
    ASCDryRun.recordBlockedWrite()
    throw ASCDryRunStop(method: request.method.rawValue, path: path)
  }
}

// MARK: - Errors

/// An App Store Connect error response (HTTP 4xx/5xx) with Apple's error entries.
public struct ASCError: Error, Sendable {
  public struct Entry: Sendable, Decodable {
    public let title: String
    public let detail: String
  }

  public let statusCode: Int
  public let errors: [Entry]
  /// Hourly limit and remaining requests from the `X-Rate-Limit` header, when present.
  public let rateLimit: (limit: Int, remaining: Int)?

  /// The `ASCError` behind an error thrown by a generated operation (the runtime wraps
  /// middleware errors in `ClientError`), or nil.
  public static func from(_ error: Error) -> ASCError? {
    if let error = error as? ASCError { return error }
    return (error as? ClientError)?.underlyingError as? ASCError
  }

  /// Whether `error` is Apple saying a to-one related object doesn't exist, which some
  /// endpoints answer with HTTP 404 and others with `{"data": null}` (failing to decode the
  /// spec's non-optional `data`).
  public static func isMissingRelated(_ error: Error) -> Bool {
    if from(error)?.statusCode == 404 { return true }
    return (error as? ClientError)?.underlyingError is DecodingError
  }
}

/// The error behind one a generated operation threw, or nil when `error` isn't the runtime's
/// wrapper. The runtime wraps transport and decoding failures in `ClientError`, whose
/// description dumps the operation input, request and response: no message for a user.
public func ascUnderlyingError(_ error: Error) -> Error? {
  (error as? ClientError)?.underlyingError
}

struct ErrorMiddleware: ClientMiddleware {
  private struct Document: Decodable {
    let errors: [ASCError.Entry]?
  }

  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    let (response, responseBody) = try await next(request, body, baseURL)
    ASCRateLimit.recorder?.header = rateLimitHeader.flatMap { response.headerFields[$0] }
    guard response.status.code >= 400 else { return (response, responseBody) }
    var data = Data()
    if let responseBody {
      data = try await Data(collecting: responseBody, upTo: 1 << 20)
    }
    // An unparseable error body still yields the status code.
    let document = try? JSONDecoder().decode(Document.self, from: data)
    throw ASCError(
      statusCode: response.status.code,
      errors: document?.errors ?? [],
      rateLimit: rateLimitHeader.flatMap { response.headerFields[$0] }.flatMap(parseRateLimit))
  }

  private let rateLimitHeader = HTTPField.Name("X-Rate-Limit")

  /// `user-hour-lim:3600;user-hour-rem:3599;`
  private func parseRateLimit(_ header: String) -> (limit: Int, remaining: Int)? {
    var values: [String: Int] = [:]
    for part in header.split(separator: ";") {
      let pair = part.split(separator: ":")
      if pair.count == 2, let value = Int(pair[1]) { values[String(pair[0])] = value }
    }
    guard let limit = values["user-hour-lim"], let remaining = values["user-hour-rem"] else { return nil }
    return (limit, remaining)
  }
}

// MARK: - Rate limit

/// The `X-Rate-Limit` header (`user-hour-lim:3600;user-hour-rem:3599;`), which the spec doesn't
/// document, so generated responses don't expose it.
public enum ASCRateLimit {
  final class Recorder: @unchecked Sendable {
    private let lock = NSLock()
    private var value: String?

    var header: String? {
      get { lock.withLock { value } }
      set { lock.withLock { value = newValue } }
    }
  }

  @TaskLocal static var recorder: Recorder?

  /// Runs `operation` and returns the `X-Rate-Limit` header of its last response.
  public static func header<T>(of operation: () async throws -> T) async throws -> String? {
    let recorder = Recorder()
    _ = try await $recorder.withValue(recorder) { try await operation() }
    return recorder.header
  }
}

/// Waits out App Store Connect's hourly request limit instead of failing. A 429 response says
/// when the quota frees up again (`Retry-After`, in seconds; seen live: 2,186), so the request is
/// sent again after that. Concurrent requests share one wait and one notice.
public struct ASCRateLimitWait: Sendable {
  /// The most this process waits in total; past it, a 429 is returned as an error. nil waits as
  /// long as Apple asks.
  public var maxTotalWait: TimeInterval?
  /// Called with the time waiting ends when a wait starts or grows, and with nil when requests
  /// go through again.
  public var onWait: @Sendable (Date?) -> Void

  public init(maxTotalWait: TimeInterval?, onWait: @escaping @Sendable (Date?) -> Void) {
    self.maxTotalWait = maxTotalWait
    self.onWait = onWait
  }
}

/// The shared state of a rate limit wait: when requests may go out again, and how long this
/// process has waited so far.
actor RateLimitGate {
  static let shared = RateLimitGate()

  private var resumeAt: Date?
  private var totalWaited: TimeInterval = 0
  private var isWaiting = false

  /// When requests may go out again, if that's still ahead.
  var pendingResume: Date? { resumeAt.flatMap { $0 > Date() ? $0 : nil } }

  /// Starts or extends the wait to `deadline`, unless that would take the total past `cap`.
  /// Returns whether to wait, and whether to announce it: when a wait starts, or grows by a
  /// minute or more (concurrent 429s arrive milliseconds apart, each a hair later).
  func wait(until deadline: Date, cap: TimeInterval?) -> (wait: Bool, announce: Bool) {
    let start = pendingResume ?? Date()
    let added = max(0, deadline.timeIntervalSince(start))
    if let cap, totalWaited + added > cap { return (false, false) }
    totalWaited += added
    let announce = !isWaiting || deadline.timeIntervalSince(resumeAt ?? .distantPast) >= 60
    if deadline > (resumeAt ?? .distantPast) { resumeAt = deadline }
    isWaiting = true
    return (true, announce)
  }

  /// Called after a request went through; true once per wait, to announce the end.
  func finish() -> Bool {
    guard isWaiting else { return false }
    isWaiting = false
    resumeAt = nil
    return true
  }
}

struct RateLimitWaitMiddleware: ClientMiddleware {
  let policy: ASCRateLimitWait
  var gate = RateLimitGate.shared

  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    while true {
      // Don't spend a request while another one already knows the quota is gone.
      if let resume = await gate.pendingResume {
        try await Task.sleep(for: .seconds(resume.timeIntervalSinceNow))
      }
      let (response, responseBody) = try await next(request, body, baseURL)
      guard response.status.code == 429, body?.iterationBehavior != .single else {
        if await gate.finish() { policy.onWait(nil) }
        return (response, responseBody)
      }
      let seconds = response.headerFields[.retryAfter].flatMap(TimeInterval.init) ?? 60
      let decision = await gate.wait(until: Date().addingTimeInterval(seconds), cap: policy.maxTotalWait)
      guard decision.wait else { return (response, responseBody) }
      if decision.announce, let resume = await gate.pendingResume { policy.onWait(resume) }
    }
  }
}

// MARK: - Pagination

/// Apple's list endpoints page through `links.next`, a full URL the spec models as no parameter
/// at all. `allPages` replays the same generated operation with the request path swapped for
/// that URL, which works for every list operation without per-endpoint cursor plumbing.
public enum ASCPaging {
  @TaskLocal static var nextPageURL: URL?

  /// Fetches the first page with `fetch`, then every page `next` links to.
  public static func allPages<Page: Sendable>(
    next: (Page) -> String?, _ fetch: () async throws -> Page
  ) async throws -> [Page] {
    var pages = [try await fetch()]
    while let link = next(pages[pages.count - 1]) {
      pages.append(try await page(link, fetch))
    }
    return pages
  }

  /// Fetches the page a `links.next` URL points to by replaying `fetch` (the first page when
  /// `link` is nil), for callers that load pages on demand.
  public static func page<Page: Sendable>(_ link: String?, _ fetch: () async throws -> Page) async throws -> Page {
    guard let link, let url = URL(string: link) else { return try await fetch() }
    return try await $nextPageURL.withValue(url) { try await fetch() }
  }
}

struct PagingMiddleware: ClientMiddleware {
  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    guard let url = ASCPaging.nextPageURL,
      let components = URLComponents(url: url, resolvingAgainstBaseURL: false)
    else {
      return try await next(request, body, baseURL)
    }
    var request = request
    request.path = components.percentEncodedPath + (components.percentEncodedQuery.map { "?" + $0 } ?? "")
    return try await next(request, body, baseURL)
  }
}

// MARK: - Explicit nulls

/// The generated request types omit nil properties, but Apple clears some values only when they
/// are sent as JSON `null` (an in-app event's badge, an introductory offer's end date, a
/// version's build relationship). `sending` runs one generated operation with the given key
/// paths of its JSON body set to null.
public enum ASCNulls {
  @TaskLocal static var paths: [[String]] = []

  /// Runs `operation` with each key path (`["data", "attributes", "badge"]`) of its request
  /// body set to `null`; missing intermediate objects are created.
  public static func sending<T: Sendable>(_ paths: [[String]], _ operation: () async throws -> T) async throws -> T {
    try await $paths.withValue(paths) { try await operation() }
  }
}

struct NullsMiddleware: ClientMiddleware {
  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    let paths = ASCNulls.paths
    guard !paths.isEmpty, let body else { return try await next(request, body, baseURL) }
    let data = try await Data(collecting: body, upTo: 16 << 20)
    guard var json = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
      return try await next(request, HTTPBody(data), baseURL)
    }
    for path in paths { setNull(&json, at: path[...]) }
    let patched = try JSONSerialization.data(withJSONObject: json)
    var request = request
    if request.headerFields[.contentLength] != nil {
      request.headerFields[.contentLength] = String(patched.count)
    }
    return try await next(request, HTTPBody(patched), baseURL)
  }

  private func setNull(_ object: inout [String: Any], at path: ArraySlice<String>) {
    guard let key = path.first else { return }
    if path.count == 1 {
      object[key] = NSNull()
    } else {
      var child = object[key] as? [String: Any] ?? [:]
      setNull(&child, at: path.dropFirst())
      object[key] = child
    }
  }
}

// MARK: - Authentication

/// Signs ES256 tokens for the App Store Connect API and reuses each for most of its 20 minutes.
actor TokenStore {
  private let credentials: ASCCredentials
  private let key: P256.Signing.PrivateKey
  private var token: (value: String, expires: Date)?

  init(credentials: ASCCredentials, key: P256.Signing.PrivateKey) {
    self.credentials = credentials
    self.key = key
  }

  func current() throws -> String {
    if let token, token.expires.timeIntervalSinceNow > 60 { return token.value }
    let now = Date()
    let expires = now.addingTimeInterval(20 * 60)
    let header = try JSONSerialization.data(withJSONObject: ["alg": "ES256", "kid": credentials.keyID, "typ": "JWT"])
    let claims = try JSONSerialization.data(withJSONObject: [
      "iss": credentials.issuerID, "aud": "appstoreconnect-v1",
      "iat": Int(now.timeIntervalSince1970), "exp": Int(expires.timeIntervalSince1970),
    ])
    let input = base64URL(header) + "." + base64URL(claims)
    let signature = try key.signature(for: Data(input.utf8)).rawRepresentation
    let value = input + "." + base64URL(signature)
    token = (value, expires)
    return value
  }

  private func base64URL(_ data: Data) -> String {
    data.base64EncodedString()
      .replacingOccurrences(of: "+", with: "-")
      .replacingOccurrences(of: "/", with: "_")
      .replacingOccurrences(of: "=", with: "")
  }
}

struct JWTMiddleware: ClientMiddleware {
  let tokens: TokenStore

  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    var request = request
    request.headerFields[.authorization] = "Bearer \(try await tokens.current())"
    return try await next(request, body, baseURL)
  }
}

// MARK: - Dates

/// Apple's timestamps come with and without fractional seconds; the runtime's default
/// transcoder accepts only the latter.
struct FlexibleISO8601DateTranscoder: DateTranscoder {
  func encode(_ date: Date) throws -> String {
    date.formatted(.iso8601)
  }

  func decode(_ string: String) throws -> Date {
    if let date = try? Date(string, strategy: .iso8601) { return date }
    if let date = try? Date(string, strategy: Date.ISO8601FormatStyle(includingFractionalSeconds: true)) { return date }
    throw DecodingError.dataCorrupted(.init(codingPath: [], debugDescription: "Invalid ISO 8601 date: \(string)"))
  }
}
