import CryptoKit
import Foundation
import HTTPTypes
import OpenAPIRuntime
import OpenAPIURLSession

// App Store Connect API client generated by swift-openapi-generator from Apple's own spec
// (openapi.json, prepared by Scripts/prepare-asc-spec.swift; generated paths are listed in
// openapi-generator-config.yaml). It replaces asc-swift one command at a time.

public typealias ASCClient = Client

public struct ASCCredentials: Sendable {
  public let keyID: String
  public let issuerID: String
  public let privateKeyPEM: String

  public init(keyID: String, issuerID: String, privateKeyPEM: String) {
    self.keyID = keyID
    self.issuerID = issuerID
    self.privateKeyPEM = privateKeyPEM
  }
}

extension Client {
  /// A client for api.appstoreconnect.apple.com: every request is signed with a JWT, every error
  /// response is thrown as an `ASCError`, and `ASCPaging.allPages` can follow `links.next`.
  public static func appStoreConnect(credentials: ASCCredentials) throws -> Client {
    let key = try P256.Signing.PrivateKey(pemRepresentation: credentials.privateKeyPEM)
    return Client(
      serverURL: try Servers.Server1.url(),
      configuration: Configuration(dateTranscoder: FlexibleISO8601DateTranscoder()),
      transport: URLSessionTransport(),
      middlewares: [
        ErrorMiddleware(),
        PagingMiddleware(),
        JWTMiddleware(tokens: TokenStore(credentials: credentials, key: key)),
      ]
    )
  }
}

// MARK: - Errors

/// An App Store Connect error response (HTTP 4xx/5xx) with Apple's error entries.
public struct ASCError: Error, Sendable {
  public struct Entry: Sendable, Decodable {
    public let title: String
    public let detail: String
  }

  public let statusCode: Int
  public let errors: [Entry]
  /// Hourly limit and remaining requests from the `X-Rate-Limit` header, when present.
  public let rateLimit: (limit: Int, remaining: Int)?

  /// The `ASCError` behind an error thrown by a generated operation (the runtime wraps
  /// middleware errors in `ClientError`), or nil.
  public static func from(_ error: Error) -> ASCError? {
    if let error = error as? ASCError { return error }
    return (error as? ClientError)?.underlyingError as? ASCError
  }

  /// Whether `error` is Apple saying a to-one related object doesn't exist, which some
  /// endpoints answer with HTTP 404 and others with `{"data": null}` (failing to decode the
  /// spec's non-optional `data`).
  public static func isMissingRelated(_ error: Error) -> Bool {
    if from(error)?.statusCode == 404 { return true }
    return (error as? ClientError)?.underlyingError is DecodingError
  }
}

struct ErrorMiddleware: ClientMiddleware {
  private struct Document: Decodable {
    let errors: [ASCError.Entry]?
  }

  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    let (response, responseBody) = try await next(request, body, baseURL)
    ASCRateLimit.recorder?.header = rateLimitHeader.flatMap { response.headerFields[$0] }
    guard response.status.code >= 400 else { return (response, responseBody) }
    var data = Data()
    if let responseBody {
      data = try await Data(collecting: responseBody, upTo: 1 << 20)
    }
    // An unparseable error body still yields the status code.
    let document = try? JSONDecoder().decode(Document.self, from: data)
    throw ASCError(
      statusCode: response.status.code,
      errors: document?.errors ?? [],
      rateLimit: rateLimitHeader.flatMap { response.headerFields[$0] }.flatMap(parseRateLimit))
  }

  private let rateLimitHeader = HTTPField.Name("X-Rate-Limit")

  /// `user-hour-lim:3600;user-hour-rem:3599;`
  private func parseRateLimit(_ header: String) -> (limit: Int, remaining: Int)? {
    var values: [String: Int] = [:]
    for part in header.split(separator: ";") {
      let pair = part.split(separator: ":")
      if pair.count == 2, let value = Int(pair[1]) { values[String(pair[0])] = value }
    }
    guard let limit = values["user-hour-lim"], let remaining = values["user-hour-rem"] else { return nil }
    return (limit, remaining)
  }
}

// MARK: - Rate limit

/// The `X-Rate-Limit` header (`user-hour-lim:3600;user-hour-rem:3599;`), which the spec doesn't
/// document, so generated responses don't expose it.
public enum ASCRateLimit {
  final class Recorder: @unchecked Sendable {
    private let lock = NSLock()
    private var value: String?

    var header: String? {
      get { lock.withLock { value } }
      set { lock.withLock { value = newValue } }
    }
  }

  @TaskLocal static var recorder: Recorder?

  /// Runs `operation` and returns the `X-Rate-Limit` header of its last response.
  public static func header<T>(of operation: () async throws -> T) async throws -> String? {
    let recorder = Recorder()
    _ = try await $recorder.withValue(recorder) { try await operation() }
    return recorder.header
  }
}

// MARK: - Pagination

/// Apple's list endpoints page through `links.next`, a full URL the spec models as no parameter
/// at all. `allPages` replays the same generated operation with the request path swapped for
/// that URL, which works for every list operation without per-endpoint cursor plumbing.
public enum ASCPaging {
  @TaskLocal static var nextPageURL: URL?

  /// Fetches the first page with `fetch`, then every page `next` links to.
  public static func allPages<Page: Sendable>(
    next: (Page) -> String?, _ fetch: () async throws -> Page
  ) async throws -> [Page] {
    var pages = [try await fetch()]
    while let link = next(pages[pages.count - 1]) {
      pages.append(try await page(link, fetch))
    }
    return pages
  }

  /// Fetches the page a `links.next` URL points to by replaying `fetch` (the first page when
  /// `link` is nil), for callers that load pages on demand.
  public static func page<Page: Sendable>(_ link: String?, _ fetch: () async throws -> Page) async throws -> Page {
    guard let link, let url = URL(string: link) else { return try await fetch() }
    return try await $nextPageURL.withValue(url) { try await fetch() }
  }
}

struct PagingMiddleware: ClientMiddleware {
  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    guard let url = ASCPaging.nextPageURL,
      let components = URLComponents(url: url, resolvingAgainstBaseURL: false)
    else {
      return try await next(request, body, baseURL)
    }
    var request = request
    request.path = components.percentEncodedPath + (components.percentEncodedQuery.map { "?" + $0 } ?? "")
    return try await next(request, body, baseURL)
  }
}

// MARK: - Authentication

/// Signs ES256 tokens for the App Store Connect API and reuses each for most of its 20 minutes.
actor TokenStore {
  private let credentials: ASCCredentials
  private let key: P256.Signing.PrivateKey
  private var token: (value: String, expires: Date)?

  init(credentials: ASCCredentials, key: P256.Signing.PrivateKey) {
    self.credentials = credentials
    self.key = key
  }

  func current() throws -> String {
    if let token, token.expires.timeIntervalSinceNow > 60 { return token.value }
    let now = Date()
    let expires = now.addingTimeInterval(20 * 60)
    let header = try JSONSerialization.data(withJSONObject: ["alg": "ES256", "kid": credentials.keyID, "typ": "JWT"])
    let claims = try JSONSerialization.data(withJSONObject: [
      "iss": credentials.issuerID, "aud": "appstoreconnect-v1",
      "iat": Int(now.timeIntervalSince1970), "exp": Int(expires.timeIntervalSince1970),
    ])
    let input = base64URL(header) + "." + base64URL(claims)
    let signature = try key.signature(for: Data(input.utf8)).rawRepresentation
    let value = input + "." + base64URL(signature)
    token = (value, expires)
    return value
  }

  private func base64URL(_ data: Data) -> String {
    data.base64EncodedString()
      .replacingOccurrences(of: "+", with: "-")
      .replacingOccurrences(of: "/", with: "_")
      .replacingOccurrences(of: "=", with: "")
  }
}

struct JWTMiddleware: ClientMiddleware {
  let tokens: TokenStore

  func intercept(
    _ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String,
    next: @Sendable (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    var request = request
    request.headerFields[.authorization] = "Bearer \(try await tokens.current())"
    return try await next(request, body, baseURL)
  }
}

// MARK: - Dates

/// Apple's timestamps come with and without fractional seconds; the runtime's default
/// transcoder accepts only the latter.
struct FlexibleISO8601DateTranscoder: DateTranscoder {
  func encode(_ date: Date) throws -> String {
    date.formatted(.iso8601)
  }

  func decode(_ string: String) throws -> Date {
    if let date = try? Date(string, strategy: .iso8601) { return date }
    if let date = try? Date(string, strategy: Date.ISO8601FormatStyle(includingFractionalSeconds: true)) { return date }
    throw DecodingError.dataCorrupted(.init(codingPath: [], debugDescription: "Invalid ISO 8601 date: \(string)"))
  }
}
