// Prepares Apple's App Store Connect OpenAPI spec for swift-openapi-generator: writes it to
// Sources/ASCKit/openapi.json and regenerates the nameOverrides section of
// Sources/ASCKit/openapi-generator-config.yaml (the rest of that file is left as is).
//
//   swift Scripts/prepare-asc-spec.swift ~/Downloads/openapi.oas.json
//
// Download the spec from https://developer.apple.com/documentation/appstoreconnectapi (OpenAPI
// specification link). Changes made to it:
// - String enums inside components/schemas become plain strings. The generator's enums are
//   closed, so a value Apple's spec does not list (it has happened: placement state ACTIVE in
//   4.5.1) would fail decoding of the whole response. Enums in query parameters stay typed:
//   they only shape requests. Empty parameter enums (no cases, which wouldn't compile) are dropped.
// - Bracketed parameter names and descending sort values get readable Swift names
//   (`filter[bundleId]` → `filterBundleId`, `-uploadedDate` → `minusUploadedDate`) through the
//   config's nameOverrides.
import Foundation

guard CommandLine.arguments.count == 2 else {
  print("usage: swift Scripts/prepare-asc-spec.swift <path to Apple's openapi.oas.json>")
  exit(2)
}

let input = URL(fileURLWithPath: (CommandLine.arguments[1] as NSString).expandingTildeInPath)
let kitDirectory = URL(fileURLWithPath: #filePath)
  .deletingLastPathComponent().deletingLastPathComponent()
  .appendingPathComponent("Sources/ASCKit")
let output = kitDirectory.appendingPathComponent("openapi.json")
let configFile = kitDirectory.appendingPathComponent("openapi-generator-config.yaml")

guard var spec = try JSONSerialization.jsonObject(with: Data(contentsOf: input)) as? [String: Any],
  var components = spec["components"] as? [String: Any],
  let schemas = components["schemas"] as? [String: Any]
else {
  print("Not an OpenAPI document with components/schemas: \(input.path)")
  exit(1)
}

var openedEnums = 0

func openEnums(_ value: Any) -> Any {
  if var object = value as? [String: Any] {
    if object["enum"] != nil, (object["type"] as? String) == "string" {
      object["enum"] = nil
      openedEnums += 1
    }
    return object.mapValues(openEnums)
  }
  if let array = value as? [Any] {
    return array.map(openEnums)
  }
  return value
}

components["schemas"] = openEnums(schemas)
spec["components"] = components

// Parameters with an empty enum (e.g. `fields[appKeywords]`: AppKeyword has no attributes) would
// generate an enum with no cases, which doesn't compile; make them plain strings.
var emptyEnums = 0

func dropEmptyEnums(_ value: Any) -> Any {
  if var object = value as? [String: Any] {
    if let values = object["enum"] as? [Any], values.isEmpty {
      object["enum"] = nil
      emptyEnums += 1
    }
    return object.mapValues(dropEmptyEnums)
  }
  if let array = value as? [Any] {
    return array.map(dropEmptyEnums)
  }
  return value
}

spec["paths"] = dropEmptyEnums(spec["paths"] ?? [:])

let data = try JSONSerialization.data(withJSONObject: spec, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
try data.write(to: output)
let version = (spec["info"] as? [String: Any])?["version"] as? String ?? "?"
print("Wrote \(output.path) (spec \(version), \(openedEnums) schema enums opened, \(emptyEnums) empty parameter enums dropped)")

// Every bracketed parameter name in the spec, e.g. `filter[appStoreVersions.platform]`.
var bracketed = Set<String>()
for operations in (spec["paths"] as? [String: Any] ?? [:]).values {
  for operation in (operations as? [String: Any] ?? [:]).values {
    for parameter in (operation as? [String: Any])?["parameters"] as? [[String: Any]] ?? [] {
      if let name = parameter["name"] as? String, name.contains("[") { bracketed.insert(name) }
      // Descending sort values, e.g. `-uploadedDate`.
      let items = (parameter["schema"] as? [String: Any])?["items"] as? [String: Any]
      for value in items?["enum"] as? [String] ?? [] where value.hasPrefix("-") { bracketed.insert(value) }
    }
  }
}

/// `filter[appStoreVersions.platform]` → `filterAppStoreVersionsPlatform`, `-uploadedDate` → `minusUploadedDate`
func swiftName(_ name: String) -> String {
  let words = (name.hasPrefix("-") ? ["minus"] : [])
    + name.split(whereSeparator: { !$0.isLetter && !$0.isNumber }).map(String.init)
  return words.enumerated().map { $0.offset == 0 ? $0.element : $0.element.prefix(1).uppercased() + $0.element.dropFirst() }.joined()
}

let marker = "# --- nameOverrides: generated by Scripts/prepare-asc-spec.swift, do not edit below ---"
let config = try String(contentsOf: configFile, encoding: .utf8)
let head = config.components(separatedBy: marker)[0].trimmingCharacters(in: .whitespacesAndNewlines)
let overrides = bracketed.sorted().map { "  \"\($0)\": \(swiftName($0))" }.joined(separator: "\n")
try (head + "\n\n" + marker + "\nnameOverrides:\n" + overrides + "\n").write(to: configFile, atomically: true, encoding: .utf8)
print("Wrote \(bracketed.count) nameOverrides to \(configFile.path)")
